#include <exception>
#include "test_utils.hpp"

int main()
{
    test_assert(true);

    return 0;
}